import { StyleSheet } from 'react-native';
import { colors, commonStyles, spacing, typography, SCREEN_HEIGHT } from '@theme';

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 24, gap: 24 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16, backgroundColor: '#F8F9FB' },
  loadingText: { fontSize: 12, fontWeight: 'bold', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 2 },
  successBox: { backgroundColor: '#ecfdf5', borderWidth: 1, borderColor: '#d1fae5', padding: 16, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 12 },
  successText: { color: '#059669', fontSize: 12, fontWeight: 'bold' },
  errorBox: { backgroundColor: '#fef2f2', borderWidth: 1, borderColor: '#fee2e2', padding: 16, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 12 },
  errorText: { color: '#dc2626', fontSize: 14, fontWeight: 'bold', textAlign: 'center' },
  card: { backgroundColor: '#ffffff', borderRadius: 32, padding: 24, borderWidth: 1, borderColor: '#f3f4f6', elevation: 2 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  cardTag: { fontSize: 10, fontWeight: '900', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 2 },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  statusText: { fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  draftBadge: { backgroundColor: '#f3f4f6' },
  draftText: { color: '#4b5563' },
  submittedBadge: { backgroundColor: '#eff6ff' },
  submittedText: { color: '#2563eb' },
  cancelledBadge: { backgroundColor: '#fef2f2' },
  cancelledText: { color: '#dc2626' },
  editButton: { padding: 8, backgroundColor: '#eff6ff', borderRadius: 12 },
  cancelEditButton: { padding: 8, backgroundColor: '#f9fafb', borderRadius: 12 },
  form: { gap: 16 },
  inputGroup: { gap: 6 },
  label: { fontSize: 10, fontWeight: 'bold', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1, marginLeft: 4 },
  inputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f9fafb', borderRadius: 16, paddingHorizontal: 16 },
  inputIcon: { marginRight: 12 },
  input: { flex: 1, paddingVertical: 14, fontSize: 14, fontWeight: 'bold', color: '#111827' },
  inputDisabled: { opacity: 0.6, color: '#6b7280' },
  gridRow: { flexDirection: 'row', gap: 12 },
  itemsList: { gap: 16, marginBottom: 24 },
  itemCard: { backgroundColor: '#f9fafb', borderRadius: 24, padding: 16, gap: 12 },
  itemHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  itemIconBox: { width: 40, height: 40, backgroundColor: '#ffffff', borderRadius: 12, alignItems: 'center', justifyContent: 'center', elevation: 1 },
  itemMeta: { flex: 1 },
  itemName: { fontSize: 14, fontWeight: 'bold', color: '#111827' },
  itemCode: { fontSize: 10, fontWeight: 'bold', color: '#9ca3af', textTransform: 'uppercase' },
  itemPriceInfo: { alignItems: 'flex-end' },
  itemAmount: { fontSize: 14, fontWeight: '900', color: '#111827' },
  itemRate: { fontSize: 10, color: '#9ca3af', fontWeight: 'bold' },
  itemTaxBadge: { paddingHorizontal: 8, paddingVertical: 2, backgroundColor: '#ecfdf5', alignSelf: 'flex-start', borderRadius: 6, marginLeft: 52 },
  itemTaxText: { fontSize: 9, color: '#059669', fontWeight: 'bold' },
  itemEditForm: { paddingTop: 12, borderTopWidth: 1, borderTopColor: '#f3f4f6', gap: 12 },
  gridCol: { flex: 1, gap: 4 },
  subLabel: { fontSize: 9, fontWeight: 'bold', color: '#9ca3af', textTransform: 'uppercase', marginLeft: 4 },
  gridInput: { backgroundColor: '#ffffff', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, fontSize: 12, fontWeight: 'bold', color: '#111827' },
  totals: { paddingTop: 16, borderTopWidth: 1, borderTopColor: '#f9fafb', gap: 8 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between' },
  totalLabel: { fontSize: 10, fontWeight: 'bold', color: '#9ca3af', textTransform: 'uppercase' },
  totalValue: { fontSize: 12, fontWeight: 'bold', color: '#111827' },
  grandTotalRow: { marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#f3f4f6' },
  grandTotalLabel: { fontSize: 12, fontWeight: '900', color: '#111827', textTransform: 'uppercase' },
  grandTotalValue: { fontSize: 18, fontWeight: '900', color: '#2563eb' },
  footerActions: { position: 'absolute', bottom: 24, left: 24, right: 24 },
  buttonRow: { flexDirection: 'row', gap: 12 },
  cancelBtn: { flex: 1, backgroundColor: '#f3f4f6', paddingVertical: 16, borderRadius: 20, alignItems: 'center' },
  cancelBtnText: { color: '#4b5563', fontWeight: 'bold', fontSize: 14 },
  saveBtn: { flex: 2, backgroundColor: '#2563eb', paddingVertical: 16, borderRadius: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, elevation: 4 },
  saveBtnText: { color: '#ffffff', fontWeight: 'bold', fontSize: 14 },
  submitBtn: { backgroundColor: '#16a34a', paddingVertical: 16, borderRadius: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, elevation: 4 },
  submitBtnText: { color: '#ffffff', fontWeight: 'bold', fontSize: 14 },
  multiActionRow: { flexDirection: 'row', gap: 12 },
  secondaryActionBtn: { flex: 1, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#f3f4f6', borderRadius: 20, height: 56, alignItems: 'center', justifyContent: 'center', elevation: 2, gap: 4 },
  secondaryActionText: { fontSize: 10, fontWeight: 'bold', color: '#4b5563' },
  primaryActionBtn: { flex: 1.5, backgroundColor: '#2563eb', borderRadius: 20, height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, elevation: 4 },
  primaryActionText: { color: '#ffffff', fontWeight: 'bold', fontSize: 14 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContent: { backgroundColor: '#ffffff', borderTopLeftRadius: 32, borderTopRightRadius: 32, maxHeight: SCREEN_HEIGHT * 0.8, paddingBottom: 40 },
  modalHeader: { padding: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: 12, gap: 12, justifyContent: 'space-between' },
  gridActionItem: { width: '30%', backgroundColor: '#ffffff', borderRadius: 20, padding: 16, alignItems: 'center', justifyContent: 'center', gap: 10, borderWidth: 1, borderColor: '#f3f4f6' },
  gridIconBox: { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center', elevation: 1 },
  gridActionText: { fontSize: 10, fontWeight: '900', color: '#111827', textAlign: 'center' },
});

export default styles;