import { StyleSheet } from 'react-native';
import { moderateScale, colors, spacing, borderRadius, typography, shadow } from '../../../../core/theme';

export const styles = StyleSheet.create({
  container: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxl },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  statusRow: { alignItems: 'flex-start', marginBottom: spacing.xs },
  badge: { paddingHorizontal: spacing.md, paddingVertical: 4, borderRadius: borderRadius.round },
  badgeText: { fontSize: 10, fontWeight: '900' },
  heroCard: { backgroundColor: colors.white, borderRadius: borderRadius.xxl, padding: spacing.lg, alignItems: 'center', borderWidth: 1, borderColor: colors.border_light, ...shadow.medium },
  balanceSummary: { flexDirection: 'row', alignItems: 'center', width: '100%', justifyContent: 'space-around' },
  balanceItem: { alignItems: 'center' },
  balanceLabel: { fontSize: 9, fontWeight: 'bold', color: colors.text_tertiary },
  balanceValue: { fontSize: moderateScale(16), fontWeight: '900' },
  balanceDivider: { width: 1, height: 24, backgroundColor: colors.border_light },
  diffText: { fontSize: 11, fontWeight: 'bold', color: colors.error, marginTop: 8 },
  detailsContainer: { backgroundColor: colors.white, borderRadius: borderRadius.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.border_light, gap: spacing.md },
  fieldWrapper: { gap: 2 },
  fieldLabel: { fontSize: 9, fontWeight: 'bold', color: colors.text_tertiary, textTransform: 'uppercase' },
  fieldInputRow: { flexDirection: 'row', alignItems: 'center' },
  inputField: { fontSize: 14, fontWeight: 'bold', color: colors.text_primary, padding: 0 },
  divider: { height: 1, backgroundColor: colors.border_light },
  section: { gap: spacing.sm },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionLabel: { fontSize: 10, fontWeight: '900', color: colors.text_tertiary, textTransform: 'uppercase', letterSpacing: 1 },
  smallAddButton: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.blue_50, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  smallAddText: { fontSize: 10, fontWeight: 'bold', color: colors.primary },
  ledgerRowCard: { backgroundColor: colors.white, borderRadius: borderRadius.xl, padding: spacing.sm, borderWidth: 1, borderColor: colors.border_light, gap: spacing.xs },
  ledgerRowHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  rowNumber: { fontSize: 10, color: colors.text_tertiary },
  rowFields: { gap: spacing.xs },
  amountRow: { flexDirection: 'row', gap: spacing.sm },
  amountInput: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: borderRadius.md, paddingHorizontal: spacing.sm, height: 32 },
  amountPrefix: { fontSize: 10, color: colors.text_tertiary, marginRight: 4 },
  ledgerInput: { flex: 1, fontSize: 12, fontWeight: 'bold', color: colors.text_primary, padding: 0 },
  remarksBox: { backgroundColor: colors.white, borderRadius: borderRadius.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.border_light },
  remarksInput: { fontSize: 13, color: colors.text_secondary, padding: 0 },
  footer: { padding: spacing.lg, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border_light },
  primaryButton: { backgroundColor: colors.primary, flexDirection: 'row', height: 50, borderRadius: borderRadius.xl, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, ...shadow.medium },
  buttonText: { color: colors.white, fontSize: 16, fontWeight: 'bold' },
  disabledSection: { opacity: 0.8 },
  submittedBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, height: 50 },
  submittedText: { fontSize: 14, fontWeight: 'bold', color: colors.success },
});
