import { StyleSheet } from 'react-native';
import { moderateScale, colors, spacing, borderRadius, typography, shadow } from '../../../../core/theme';

export const styles = StyleSheet.create({
  container: { padding: spacing.lg, gap: spacing.xl, paddingBottom: spacing.xxl },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { color: colors.error, fontSize: 14, fontWeight: 'bold' },
  heroCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xxl,
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border_light,
    ...shadow.medium,
    position: 'relative',
  },
  headerRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  badge: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: borderRadius.round },
  badgeText: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.5 },
  amountHero: { fontSize: moderateScale(32), fontWeight: '900', color: colors.text_primary, letterSpacing: -1 },
  metaText: { fontSize: 11, color: colors.text_tertiary, fontWeight: 'bold', textTransform: 'uppercase' },
  editIconBtn: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    padding: 8,
    backgroundColor: colors.blue_50,
    borderRadius: borderRadius.round,
  },
  detailsContainer: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xxl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border_light,
    gap: spacing.lg,
    ...shadow.small,
  },
  fieldWrapper: { gap: 4 },
  fieldLabel: { fontSize: 9, fontWeight: 'bold', color: colors.text_tertiary, textTransform: 'uppercase', letterSpacing: 1 },
  fieldValueRow: { flexDirection: 'row', alignItems: 'center' },
  fieldValue: { fontSize: 14, fontWeight: 'bold', color: colors.text_primary },
  divider: { height: 1, backgroundColor: colors.border_light, marginVertical: spacing.xs },
  section: { gap: spacing.md },
  sectionLabel: { fontSize: 10, fontWeight: '900', color: colors.text_tertiary, textTransform: 'uppercase', letterSpacing: 2, marginLeft: spacing.xs },
  accountList: { backgroundColor: colors.white, borderRadius: borderRadius.xl, borderWidth: 1, borderColor: colors.border_light, overflow: 'hidden', ...shadow.small },
  accountCard: { flexDirection: 'row', padding: spacing.md, alignItems: 'center', justifyContent: 'space-between' },
  borderBottom: { borderBottomWidth: 1, borderBottomColor: colors.border_light },
  accName: { fontSize: 13, fontWeight: 'bold', color: colors.text_primary },
  partyRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  accParty: { fontSize: 10, color: colors.text_tertiary, fontWeight: '600' },
  accValue: { fontSize: 13, fontWeight: '900' },
  remarksBox: { backgroundColor: colors.purple_50 + '30', borderRadius: borderRadius.xl, padding: spacing.lg, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.purple_200 },
  remarksContent: { fontSize: 13, color: colors.text_secondary, lineHeight: 20, fontStyle: 'italic' },
  footer: { padding: spacing.lg, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border_light },
  primaryButton: { backgroundColor: colors.primary, flexDirection: 'row', height: moderateScale(54), borderRadius: borderRadius.xl, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, ...shadow.medium },
  buttonText: { color: colors.white, fontSize: 16, fontWeight: 'bold' },
  submittedBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, height: 50 },
  submittedText: { fontSize: 14, fontWeight: 'bold', color: colors.success },
});
