import { StyleSheet } from 'react-native';
import { moderateScale, colors, spacing, borderRadius, typography, shadow } from '../../../../core/theme';

export const styles = StyleSheet.create({
  container: {
    padding: spacing.lg,
    gap: spacing.xl,
    paddingBottom: spacing.xxl,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
badgeSuccess: { backgroundColor: colors.success + '15' },
badgeError: { backgroundColor: colors.error + '15' },
badgeDefault: { backgroundColor: colors.neutral_600 + '15' },
badgeBlue: { backgroundColor: colors.blue_50 },

primaryText: { color: colors.primary },

flex1: { flex: 1 },
alignEnd: { alignItems: 'flex-end' },

iconSpacing: { marginRight: spacing.xs },

disabled: { opacity: 0.7 },
  heroCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xxl,
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border_light,
    ...shadow.medium,
  },
  headerRow: {
    flexDirection: 'row',
    marginBottom: spacing.xs,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.round,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  currencySymbol: {
    fontSize: moderateScale(24),
    fontWeight: '900',
    color: colors.primary,
  },
  amountHeroInput: {
    fontSize: moderateScale(32),
    fontWeight: '900',
    color: colors.text_primary,
    letterSpacing: -1,
    padding: 0,
    minWidth: moderateScale(100),
    textAlign: 'center',
  },
  heroLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    color: colors.text_tertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  detailsContainer: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xxl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border_light,
    gap: spacing.lg,
    ...shadow.small,
  },
  fieldWrapper: {
    gap: 4,
  },
  fieldLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    color: colors.text_tertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  fieldInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: moderateScale(24),
  },
  inputField: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.text_primary,
    padding: 0,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border_light,
    marginVertical: spacing.xs,
  },
  section: {
    gap: spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '900',
    color: colors.text_tertiary,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginLeft: spacing.xs,
  },
  smallAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.blue_50,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  smallAddText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.primary,
  },
  placeholderBox: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border_light,
    borderStyle: 'dashed',
    gap: spacing.sm,
  },
  placeholderText: {
    fontSize: 12,
    color: colors.text_tertiary,
    fontWeight: '600',
  },
  remarksBox: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border_light,
    ...shadow.small,
  },
  remarksInput: {
    fontSize: 13,
    color: colors.text_secondary,
    lineHeight: 20,
    padding: 0,
  },
  footer: {
    padding: spacing.lg,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border_light,
  },
  saveButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    height: moderateScale(54),
    borderRadius: borderRadius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...shadow.medium,
  },
  saveButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
